name: CI Test

on:
  pull_request:
    paths-ignore:
      - '*.commits'
      - '*.markdown'
      - '**/*.markdown'

env:
  LC_ALL: en_US.UTF-8

jobs:
  CheckSourceFormatting:
    name: Check Source Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Check Source Formatting
        shell: bash
        run: |
          pip3 install black beautysh
          find . -name '*.py' -print | xargs black --check
          find . -name 'Tiltfile' -print | xargs black --check
          find . -name '*.sh' -print | xargs beautysh -t --check
  CreateAndBuildProjects:
    name: Create and Build Projects
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up JDK8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build
        shell: bash
        env:
          GITHUB_CI: "true"
          DOCKER_NETWORK: "host"
        run: |
          export LOCALDEV_REPO=${GITHUB_WORKSPACE}
          ./tests/integration/create-build-projects.sh
  TiltupNewProjects:
    name: Tiltup new projects
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        shell: bash
        env:
          GITHUB_CI: "true"
          DOCKER_NETWORK: "host"
        run: |
          export LOCALDEV_REPO=${GITHUB_WORKSPACE}
          ./tests/functional/tiltup-new-projects.sh
  TiltUpSampleProjects:
    name: Tiltup sample projects
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        shell: bash
        env:
          GITHUB_CI: "true"
          DOCKER_NETWORK: "host"
        run: |
          export LOCALDEV_REPO=${GITHUB_WORKSPACE}
          ./tests/functional/tiltup-sample-projects.sh